/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WirUnterstuetzenRouteImport } from './routes/wir-unterstuetzen'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as KuechenmontageWilhelmshavenRouteImport } from './routes/kuechenmontage-wilhelmshaven'
import { Route as KuechenmontageInWilhelmshavenRouteImport } from './routes/kuechenmontage-in-wilhelmshaven'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as HandwerkerserviceWilhelmshavenRouteImport } from './routes/handwerkerservice-wilhelmshaven'
import { Route as HandwerkerserviceWangerlandRouteImport } from './routes/handwerkerservice-wangerland'
import { Route as HandwerkerserviceVarelRouteImport } from './routes/handwerkerservice-varel'
import { Route as HandwerkerserviceSchortensRouteImport } from './routes/handwerkerservice-schortens'
import { Route as HandwerkerserviceSandeRouteImport } from './routes/handwerkerservice-sande'
import { Route as HandwerkerserviceJeverRouteImport } from './routes/handwerkerservice-jever'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EntruempelungEntsorgungInWilhelmshavenRouteImport } from './routes/entruempelung-entsorgung-in-wilhelmshaven'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BodenverlegungWilhelmshavenRouteImport } from './routes/bodenverlegung-wilhelmshaven'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowroomIndexRouteImport } from './routes/showroom.index'
import { Route as ShowroomSlugRouteImport } from './routes/showroom.$slug'

const WirUnterstuetzenRoute = WirUnterstuetzenRouteImport.update({
  id: '/wir-unterstuetzen',
  path: '/wir-unterstuetzen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const KuechenmontageWilhelmshavenRoute =
  KuechenmontageWilhelmshavenRouteImport.update({
    id: '/kuechenmontage-wilhelmshaven',
    path: '/kuechenmontage-wilhelmshaven',
    getParentRoute: () => rootRouteImport,
  } as any)
const KuechenmontageInWilhelmshavenRoute =
  KuechenmontageInWilhelmshavenRouteImport.update({
    id: '/kuechenmontage-in-wilhelmshaven',
    path: '/kuechenmontage-in-wilhelmshaven',
    getParentRoute: () => rootRouteImport,
  } as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HandwerkerserviceWilhelmshavenRoute =
  HandwerkerserviceWilhelmshavenRouteImport.update({
    id: '/handwerkerservice-wilhelmshaven',
    path: '/handwerkerservice-wilhelmshaven',
    getParentRoute: () => rootRouteImport,
  } as any)
const HandwerkerserviceWangerlandRoute =
  HandwerkerserviceWangerlandRouteImport.update({
    id: '/handwerkerservice-wangerland',
    path: '/handwerkerservice-wangerland',
    getParentRoute: () => rootRouteImport,
  } as any)
const HandwerkerserviceVarelRoute = HandwerkerserviceVarelRouteImport.update({
  id: '/handwerkerservice-varel',
  path: '/handwerkerservice-varel',
  getParentRoute: () => rootRouteImport,
} as any)
const HandwerkerserviceSchortensRoute =
  HandwerkerserviceSchortensRouteImport.update({
    id: '/handwerkerservice-schortens',
    path: '/handwerkerservice-schortens',
    getParentRoute: () => rootRouteImport,
  } as any)
const HandwerkerserviceSandeRoute = HandwerkerserviceSandeRouteImport.update({
  id: '/handwerkerservice-sande',
  path: '/handwerkerservice-sande',
  getParentRoute: () => rootRouteImport,
} as any)
const HandwerkerserviceJeverRoute = HandwerkerserviceJeverRouteImport.update({
  id: '/handwerkerservice-jever',
  path: '/handwerkerservice-jever',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EntruempelungEntsorgungInWilhelmshavenRoute =
  EntruempelungEntsorgungInWilhelmshavenRouteImport.update({
    id: '/entruempelung-entsorgung-in-wilhelmshaven',
    path: '/entruempelung-entsorgung-in-wilhelmshaven',
    getParentRoute: () => rootRouteImport,
  } as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BodenverlegungWilhelmshavenRoute =
  BodenverlegungWilhelmshavenRouteImport.update({
    id: '/bodenverlegung-wilhelmshaven',
    path: '/bodenverlegung-wilhelmshaven',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomIndexRoute = ShowroomIndexRouteImport.update({
  id: '/showroom/',
  path: '/showroom/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomSlugRoute = ShowroomSlugRouteImport.update({
  id: '/showroom/$slug',
  path: '/showroom/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bodenverlegung-wilhelmshaven': typeof BodenverlegungWilhelmshavenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/entruempelung-entsorgung-in-wilhelmshaven': typeof EntruempelungEntsorgungInWilhelmshavenRoute
  '/faq': typeof FaqRoute
  '/handwerkerservice-jever': typeof HandwerkerserviceJeverRoute
  '/handwerkerservice-sande': typeof HandwerkerserviceSandeRoute
  '/handwerkerservice-schortens': typeof HandwerkerserviceSchortensRoute
  '/handwerkerservice-varel': typeof HandwerkerserviceVarelRoute
  '/handwerkerservice-wangerland': typeof HandwerkerserviceWangerlandRoute
  '/handwerkerservice-wilhelmshaven': typeof HandwerkerserviceWilhelmshavenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kuechenmontage-in-wilhelmshaven': typeof KuechenmontageInWilhelmshavenRoute
  '/kuechenmontage-wilhelmshaven': typeof KuechenmontageWilhelmshavenRoute
  '/partner': typeof PartnerRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/wir-unterstuetzen': typeof WirUnterstuetzenRoute
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/showroom/': typeof ShowroomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bodenverlegung-wilhelmshaven': typeof BodenverlegungWilhelmshavenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/entruempelung-entsorgung-in-wilhelmshaven': typeof EntruempelungEntsorgungInWilhelmshavenRoute
  '/faq': typeof FaqRoute
  '/handwerkerservice-jever': typeof HandwerkerserviceJeverRoute
  '/handwerkerservice-sande': typeof HandwerkerserviceSandeRoute
  '/handwerkerservice-schortens': typeof HandwerkerserviceSchortensRoute
  '/handwerkerservice-varel': typeof HandwerkerserviceVarelRoute
  '/handwerkerservice-wangerland': typeof HandwerkerserviceWangerlandRoute
  '/handwerkerservice-wilhelmshaven': typeof HandwerkerserviceWilhelmshavenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kuechenmontage-in-wilhelmshaven': typeof KuechenmontageInWilhelmshavenRoute
  '/kuechenmontage-wilhelmshaven': typeof KuechenmontageWilhelmshavenRoute
  '/partner': typeof PartnerRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/wir-unterstuetzen': typeof WirUnterstuetzenRoute
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/showroom': typeof ShowroomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bodenverlegung-wilhelmshaven': typeof BodenverlegungWilhelmshavenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/entruempelung-entsorgung-in-wilhelmshaven': typeof EntruempelungEntsorgungInWilhelmshavenRoute
  '/faq': typeof FaqRoute
  '/handwerkerservice-jever': typeof HandwerkerserviceJeverRoute
  '/handwerkerservice-sande': typeof HandwerkerserviceSandeRoute
  '/handwerkerservice-schortens': typeof HandwerkerserviceSchortensRoute
  '/handwerkerservice-varel': typeof HandwerkerserviceVarelRoute
  '/handwerkerservice-wangerland': typeof HandwerkerserviceWangerlandRoute
  '/handwerkerservice-wilhelmshaven': typeof HandwerkerserviceWilhelmshavenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kuechenmontage-in-wilhelmshaven': typeof KuechenmontageInWilhelmshavenRoute
  '/kuechenmontage-wilhelmshaven': typeof KuechenmontageWilhelmshavenRoute
  '/partner': typeof PartnerRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/wir-unterstuetzen': typeof WirUnterstuetzenRoute
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/showroom/': typeof ShowroomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bodenverlegung-wilhelmshaven'
    | '/datenschutz'
    | '/entruempelung-entsorgung-in-wilhelmshaven'
    | '/faq'
    | '/handwerkerservice-jever'
    | '/handwerkerservice-sande'
    | '/handwerkerservice-schortens'
    | '/handwerkerservice-varel'
    | '/handwerkerservice-wangerland'
    | '/handwerkerservice-wilhelmshaven'
    | '/impressum'
    | '/kontakt'
    | '/kuechenmontage-in-wilhelmshaven'
    | '/kuechenmontage-wilhelmshaven'
    | '/partner'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/wir-unterstuetzen'
    | '/showroom/$slug'
    | '/showroom/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bodenverlegung-wilhelmshaven'
    | '/datenschutz'
    | '/entruempelung-entsorgung-in-wilhelmshaven'
    | '/faq'
    | '/handwerkerservice-jever'
    | '/handwerkerservice-sande'
    | '/handwerkerservice-schortens'
    | '/handwerkerservice-varel'
    | '/handwerkerservice-wangerland'
    | '/handwerkerservice-wilhelmshaven'
    | '/impressum'
    | '/kontakt'
    | '/kuechenmontage-in-wilhelmshaven'
    | '/kuechenmontage-wilhelmshaven'
    | '/partner'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/wir-unterstuetzen'
    | '/showroom/$slug'
    | '/showroom'
  id:
    | '__root__'
    | '/'
    | '/bodenverlegung-wilhelmshaven'
    | '/datenschutz'
    | '/entruempelung-entsorgung-in-wilhelmshaven'
    | '/faq'
    | '/handwerkerservice-jever'
    | '/handwerkerservice-sande'
    | '/handwerkerservice-schortens'
    | '/handwerkerservice-varel'
    | '/handwerkerservice-wangerland'
    | '/handwerkerservice-wilhelmshaven'
    | '/impressum'
    | '/kontakt'
    | '/kuechenmontage-in-wilhelmshaven'
    | '/kuechenmontage-wilhelmshaven'
    | '/partner'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/wir-unterstuetzen'
    | '/showroom/$slug'
    | '/showroom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodenverlegungWilhelmshavenRoute: typeof BodenverlegungWilhelmshavenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EntruempelungEntsorgungInWilhelmshavenRoute: typeof EntruempelungEntsorgungInWilhelmshavenRoute
  FaqRoute: typeof FaqRoute
  HandwerkerserviceJeverRoute: typeof HandwerkerserviceJeverRoute
  HandwerkerserviceSandeRoute: typeof HandwerkerserviceSandeRoute
  HandwerkerserviceSchortensRoute: typeof HandwerkerserviceSchortensRoute
  HandwerkerserviceVarelRoute: typeof HandwerkerserviceVarelRoute
  HandwerkerserviceWangerlandRoute: typeof HandwerkerserviceWangerlandRoute
  HandwerkerserviceWilhelmshavenRoute: typeof HandwerkerserviceWilhelmshavenRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  KuechenmontageInWilhelmshavenRoute: typeof KuechenmontageInWilhelmshavenRoute
  KuechenmontageWilhelmshavenRoute: typeof KuechenmontageWilhelmshavenRoute
  PartnerRoute: typeof PartnerRoute
  PreiseRoute: typeof PreiseRoute
  ReferenzenRoute: typeof ReferenzenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberUnsRoute: typeof UeberUnsRoute
  WirUnterstuetzenRoute: typeof WirUnterstuetzenRoute
  ShowroomSlugRoute: typeof ShowroomSlugRoute
  ShowroomIndexRoute: typeof ShowroomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wir-unterstuetzen': {
      id: '/wir-unterstuetzen'
      path: '/wir-unterstuetzen'
      fullPath: '/wir-unterstuetzen'
      preLoaderRoute: typeof WirUnterstuetzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuechenmontage-wilhelmshaven': {
      id: '/kuechenmontage-wilhelmshaven'
      path: '/kuechenmontage-wilhelmshaven'
      fullPath: '/kuechenmontage-wilhelmshaven'
      preLoaderRoute: typeof KuechenmontageWilhelmshavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuechenmontage-in-wilhelmshaven': {
      id: '/kuechenmontage-in-wilhelmshaven'
      path: '/kuechenmontage-in-wilhelmshaven'
      fullPath: '/kuechenmontage-in-wilhelmshaven'
      preLoaderRoute: typeof KuechenmontageInWilhelmshavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwerkerservice-wilhelmshaven': {
      id: '/handwerkerservice-wilhelmshaven'
      path: '/handwerkerservice-wilhelmshaven'
      fullPath: '/handwerkerservice-wilhelmshaven'
      preLoaderRoute: typeof HandwerkerserviceWilhelmshavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwerkerservice-wangerland': {
      id: '/handwerkerservice-wangerland'
      path: '/handwerkerservice-wangerland'
      fullPath: '/handwerkerservice-wangerland'
      preLoaderRoute: typeof HandwerkerserviceWangerlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwerkerservice-varel': {
      id: '/handwerkerservice-varel'
      path: '/handwerkerservice-varel'
      fullPath: '/handwerkerservice-varel'
      preLoaderRoute: typeof HandwerkerserviceVarelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwerkerservice-schortens': {
      id: '/handwerkerservice-schortens'
      path: '/handwerkerservice-schortens'
      fullPath: '/handwerkerservice-schortens'
      preLoaderRoute: typeof HandwerkerserviceSchortensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwerkerservice-sande': {
      id: '/handwerkerservice-sande'
      path: '/handwerkerservice-sande'
      fullPath: '/handwerkerservice-sande'
      preLoaderRoute: typeof HandwerkerserviceSandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwerkerservice-jever': {
      id: '/handwerkerservice-jever'
      path: '/handwerkerservice-jever'
      fullPath: '/handwerkerservice-jever'
      preLoaderRoute: typeof HandwerkerserviceJeverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entruempelung-entsorgung-in-wilhelmshaven': {
      id: '/entruempelung-entsorgung-in-wilhelmshaven'
      path: '/entruempelung-entsorgung-in-wilhelmshaven'
      fullPath: '/entruempelung-entsorgung-in-wilhelmshaven'
      preLoaderRoute: typeof EntruempelungEntsorgungInWilhelmshavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodenverlegung-wilhelmshaven': {
      id: '/bodenverlegung-wilhelmshaven'
      path: '/bodenverlegung-wilhelmshaven'
      fullPath: '/bodenverlegung-wilhelmshaven'
      preLoaderRoute: typeof BodenverlegungWilhelmshavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom/': {
      id: '/showroom/'
      path: '/showroom'
      fullPath: '/showroom/'
      preLoaderRoute: typeof ShowroomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom/$slug': {
      id: '/showroom/$slug'
      path: '/showroom/$slug'
      fullPath: '/showroom/$slug'
      preLoaderRoute: typeof ShowroomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodenverlegungWilhelmshavenRoute: BodenverlegungWilhelmshavenRoute,
  DatenschutzRoute: DatenschutzRoute,
  EntruempelungEntsorgungInWilhelmshavenRoute:
    EntruempelungEntsorgungInWilhelmshavenRoute,
  FaqRoute: FaqRoute,
  HandwerkerserviceJeverRoute: HandwerkerserviceJeverRoute,
  HandwerkerserviceSandeRoute: HandwerkerserviceSandeRoute,
  HandwerkerserviceSchortensRoute: HandwerkerserviceSchortensRoute,
  HandwerkerserviceVarelRoute: HandwerkerserviceVarelRoute,
  HandwerkerserviceWangerlandRoute: HandwerkerserviceWangerlandRoute,
  HandwerkerserviceWilhelmshavenRoute: HandwerkerserviceWilhelmshavenRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  KuechenmontageInWilhelmshavenRoute: KuechenmontageInWilhelmshavenRoute,
  KuechenmontageWilhelmshavenRoute: KuechenmontageWilhelmshavenRoute,
  PartnerRoute: PartnerRoute,
  PreiseRoute: PreiseRoute,
  ReferenzenRoute: ReferenzenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberUnsRoute: UeberUnsRoute,
  WirUnterstuetzenRoute: WirUnterstuetzenRoute,
  ShowroomSlugRoute: ShowroomSlugRoute,
  ShowroomIndexRoute: ShowroomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
